CREATE DATABASE IF NOT EXISTS companydb;
USE companydb;
CREATE TABLE empleados(
    id INT(11) NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(45) DEFAULT NULL,
    salario INT(5) DEFAULT NULL,
    PRIMARY KEY(id)
)

DESCRIBE empleados;
INSERT INTO empleados VALUES
(1, 'KEYVER', 1000),
(2, 'KEYVER2', 100),
(3, 'KEYVER3', 10),
(4, 'KEYVER4', 1);
